### DISCUSSION TITLE
User error or bug with cli_parse TTP and TextFSM usage?

### DISCUSSION THREAD

**Discussion by netopsengineer** [ansible-collections/ansible.utils#49] [Q&A] [answered]
Hello,

I am trying to use the TTP and TextFSM parsers like such, this is my TTP task:

```
- name: Show ip-prefix-list.
  cli_command:
    command: show filter ip 104 entry 65535 | match "Primary Action"
  register: nokia_show_ip_prefix_info

- name: Pass text and command
  ansible.utils.cli_parse:
    text: "{{ nokia_show_ip_prefix_info['stdout'] }}"
    parser:
      name: ansible.utils.ttp
      template_path: templates/nokia_show_ip_filter_state_parser.ttp
  register: parser_output
```

I have a valid ttp parser at the template_path specified, Ansible 3.0, with 2.10.6 base installed, ttp is installed, ttp works with python which is 3.8.2, this template works with this interpreter when utilized in a python script, I am receiving output from the cli_command in the previous task, which is using the Nokia Galaxy Collection module.  I'm on Mac OS Big Sur, for what its worth.

The collections are installed into a folder specified in ansible.cfg in my project, of /collections, when I run requirements.yml, which contains the collections in question, I receive the following, making me think I'm up to date and not missing anything:

`Starting collection install process
Skipping 'ansible.netcommon' as it is already installed
Skipping 'nokia.sros' as it is already installed
Skipping 'ansible.utils' as it is already installed
`

When I run the playbook with -vvv, I receive the following

`  File "/Volumes/Seagate/codeProjects/myTestProject/collections/ansible_collections/ansible/utils/plugins/action/cli_parse.py", line 374, in run
    self._result["parsed"] = result["parsed"]
KeyError: 'parsed'
`

What am I missing?  I get the same error if I try to use TextFSM, via utils.textfsm as the parser.  Let me know if I can provide further details, would love to get this working.
