### DISCUSSION TITLE
CLI parse not producing any structured data output.

### DISCUSSION THREAD

**Discussion by carmelitox** [ansible-collections/ansible.utils#65] [Q&A]
Hello,

I have the following ttp template.

```BASH
<group name="snmp_hosts">
Notification host: {{ snmp_host_ip | _start_ }} udp-port: {{ snmp_host_port }}   VRFName: {{ vrf }}       type: {{ type }}

Notification host: {{ snmp_host_ip | _start_ }}       udp-port: {{ snmp_host_port }}   type: {{ type }}
</group>
```

which works with ttp cli with no issues:

```JSON
[
    [
        {
            "snmp_hosts": [
                {
                    "snmp_host_ip": "192.0.2.1",
                    "snmp_host_port": "162",
                    "type": "inform",
                    "vrf": "Mgmt-vrf"
                },
                {
                    "snmp_host_ip": "192.0.2.2",
                    "snmp_host_port": "162",
                    "type": "inform",
                    "vrf": "Mgmt-vrf"
                },
                {
                    "snmp_host_ip": "192.0.2.3",
                    "snmp_host_port": "162",
                    "type": "inform",
                    "vrf": "Mgmt-vrf"
                }
            ]
        }
    ]
]
```

The following Ansible playbook, does never produce structured data:

```YAML

    - name: show snmp host
      cli_command:
        command: show snmp host
      register: show_snmp_host_unstructured

    - name: "TTP Parse - show snmp host"
      ansible.utils.cli_parse:
        text: "{{ show_snmp_host_unstructured['stdout'] }}"
        parser:
          name: ansible.utils.ttp
          template_path: /opt/automation/ansible/playbooks/snmp-thing/templates/ios_show_snmp_host.ttp
      register: snmp_host

    - name: "DISPLAY VARIABLES"
      ansible.builtin.debug:
       msg: System {{ inventory_hostname }} has the following facts {{ snmp_host }}

```

I always get a empty list:

```JSON
ok: [hostname] => {
    "changed": false,
    "parsed": [
        [
            {}
        ]
    ]
}
```

As is my first time doing this, I previously tried to run the example for TTP provided in:

https://docs.ansible.com/ansible/latest/network/user_guide/cli_parsing.html#parsing-with-ttp

```YAML
    - name: "TTP Parse - show interfaces"
      ansible.utils.cli_parse:
        command: "show interfaces"
        parser:
          name: ansible.utils.ttp
          template_path: ./templates/ios_show_interfaces.ttp
        set_fact: interfaces

    - name: "DISPLAY VARIABLES"
      ansible.builtin.debug:
       msg: System {{ inventory_hostname }} has the following facts {{ interfaces }}
```

but faced the same issue, no structure data output.

My Ansible version is as follows:

```INI
ansible 2.10.7
  config file = /opt/automation/ansible/playbooks/snmp-thing/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```
I run Ansible with -vvv and I cannot see any errors or any reference to ttp that could indicate what is wrong.

Am I missing somehting? Let me know if you need more data.

Thanks.
