### ISSUE TITLE
[to_xml] Support "indent" parameter for xmltodict engine

### ISSUE THREAD

**Issue by fchiacchiaretta** [ansible-collections/ansible.utils#116]
##### SUMMARY
to_xml defaults to indenting XML documents with tabs, as xmltodict .
xmltodict library `unparse` [function](https://github.com/martinblech/xmltodict/blob/ae19c452ca000bf243bfc16274c060bf3bf7cf51/xmltodict.py#L472) supports and `indent` parameter that can be used to specify a different indent character (for example spaces).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.utils.to_xml

##### ADDITIONAL INFORMATION
The plugin should have two additional parameters:

* indent (can be "tab" or "space", default to "tab")
* indent_width (int, only used when indent="space", default to 4)

Parameters have to be parsed before sending them to `unparse` function, since this function only supports indent parameter to specify the character to use for indentation.

```yaml
- name: Define JSON data
  ansible.builtin.set_fact:
    data:
      "interface-configurations":
          "@xmlns": "http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"
          "interface-configuration":
- debug:
    msg:  "{{ data|ansible.utils.to_xml(indent="space", indent_width=2) }}"
```

If you are open to adding this feature, I am available to make a pull request for this.
