### ISSUE TITLE
Extend remove_keys and maybe others to take ansible.utils.to_paths generated output as arguments for target

### ISSUE THREAD

**Issue by flybyray** [ansible-collections/ansible.utils#155]
##### SUMMARY
Extend at least `remove_keys ` from [Recursive filter plugins remove_keys | replace_keys | keep_keys](https://github.com/ansible-collections/ansible.utils/pull/110) to support inputs for target which have the form what [ansible.utils.to_paths](https://github.com/ansible-collections/ansible.utils/blob/main/plugins/module_utils/common/to_paths.py#L21-L60) generates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- ansible.utils.remove_keys
- ansible.utils.to_paths

##### ADDITIONAL INFORMATION
If data structure is more complex and has a key which is matched by target on multiple levels you might want to be more specific which key you really want to remove.

```yaml
    ##example.yaml
    a:
      b:
        c:
          e:
          - 0
          - 1
        d:
          e:
          - True
          - False

    ##Playbook
    vars_files:
      - "example.yaml"
    tasks:
      - ansible.builtin.set_fact:
          paths: "{{ a|ansible.utils.to_paths }}"

      # TASK [ansible.builtin.set_fact] ********************************************
      # ok: [localhost] => changed=false
      #   ansible_facts:
      #     paths:
      #       b.c.e[0]: 0
      #       b.c.e[1]: 1
      #       b.d.e[0]: True
      #       b.d.e[1]: False

      - debug:
          msg:  "{{ a|ansible.utils.remove_keys(target=['^b.d.e'], matching_parameter= 'regex') }}"

      # TASK [debug] *****************************************
      # ok: [localhost] => {
      #     "msg": {
      #         "b": {
      #             "c": {
      #                 "e": [
      #                     0,
      #                     1
      #                 ]
      #             }
      #         }
      #     }
      # }

```
