### ISSUE TITLE
sub_plugins/fact_diff/native.py does not process dict objects properly

### ISSUE THREAD

**Issue by joshinryz** [ansible-collections/ansible.utils#195]
##### SUMMARY
When passing facts to fact_diff, if you add ignore_lines the process treats the dict like a list and adds its keys as strings  (removing values).

Specifically these lines: (60-69):

`            self._before = [
                line
                for line in self._before
                if not any(regex.match(str(line)) for regex in self._skip_lines)
            ]
            self._after = [
                line
                for line in self._after
                if not any(regex.match(str(line)) for regex in self._skip_lines)
            ]`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

sub_plugins/fact_diff/native.py

##### ANSIBLE VERSION

```
ansible [core 2.13.1]
```

##### STEPS TO REPRODUCE

```yaml
- name: Show the difference in json format
  ansible.utils.fact_diff:
    before: "{{ before }}"
    after: "{{ after }}"
    plugin:
      name: ansible.utils.native
      vars:
         skip_lines:
            - '^example.*'
```

##### EXPECTED RESULTS

Should properly handle dicts, instead it will break if skip_lines is included (causing two different facts to appear the same).
As it will only compare key names and not their values.
