### ISSUE TITLE
ipaddr does not recognize /25 networks with a .128 network 

### ISSUE THREAD

**Issue by joefodor** [ansible-collections/ansible.utils#359]
##### SUMMARY

When using the ansible.utils.ipaddr filter it marks a network 192.168.10.128/25 as false when it is a correct network. This works just fine when using 192.168.10.0/25 and the /24s all work. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

        subnet_gateway: "{{ subnet | ansible.utils.ipaddr('129') }}"
##### ANSIBLE VERSION

```paste below
root@1eb5427eb163:/test# ansible --version
ansible [core 2.15.12]
  config file = /test/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.19 (main, Apr 24 2024, 07:59:08) [GCC 12.2.0] (/usr/local/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
root@1eb5427eb163:/test# ansible-galaxy collection list ansible.utils

# /root/.ansible/collections/ansible_collections
Collection    Version
------------- -------
ansible.utils 5.0.0  

# /usr/local/lib/python3.9/site-packages/ansible_collections
Collection    Version
------------- -------
ansible.utils 2.12.0 
```

##### CONFIGURATION

```paste below
root@1eb5427eb163:/test# ansible-config dump --only-changed
/bin/sh: 1: less: not found
```

##### STEPS TO REPRODUCE

```yaml
- name: Test ipaddr filter issue
  hosts: localhost
  tasks:
    - name: Set subnet and prefix
      ansible.builtin.set_fact:
        subnet: 192.168.10.128/25

    - name: Calculate the gateway address manually
      ansible.builtin.set_fact:
        subnet_gateway: "{{ subnet | ansible.utils.ipaddr('129') }}"
```

##### EXPECTED RESULTS

subnet_gateway: 192.168.10.129/25

##### ACTUAL RESULTS

Makes the subnet_gateway var false 

```paste below
Loading collection ansible.utils from /root/.ansible/collections/ansible_collections/ansible/utils
ok: [localhost] => {
    "ansible_facts": {
        "subnet_gateway": false
    },
    "changed": false
}
```
