### ISSUE TITLE
Add new plugin resource_list_compare that generate the final resource list after comparing base and provided resource list and bangs

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-collections/ansible.utils#88]
##### SUMMARY

Add new plugin resource_list_compare that generates the final resource list after comparing base and provided resource list and bangs.

EXAMPLE:
```yaml
- set_fact:
    resources: resources:
        - '!all'
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
 - set_fact
      network_resource_list:
          modules:
              - 'acl_interfaces'
              - 'acls'
              - 'bgp_address_family'
              - 'bgp_global'
              - ' interfaces'
              - 'l2_interfaces'
              - 'l3_interfaces'
              - 'lacp',
              - 'lacp_interfaces'
              - 'lag_interfaces'
              - 'lldp_global',
              - 'lldp_interfaces'
              - 'logging_global'
              - 'ospf_interfaces'
              - 'ospfv2'
              - 'ospfv3'
        "prefix_lists",
        "route_maps",
        "static_routes",
        "vlans"

- name: set facts for data and criteria
  set_fact:
    final_network_resources: "{{ network_resources_list['modules']|resource_list_compare(resources) }}"
```
RESULT:
```
final_network_resources=['interfaces', 'l2_interfaces', 'l3_interfaces']
```
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```
